# Github Actions configuration file
name: Build

on:
  push:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: MSVC Environment Setup
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-x64
        path: |
          ${{github.workspace}}/build/spright.exe
